### PR TITLE
Emergency fix userprofile get

### PR DESCRIPTION
**Pull request by JAFAJ0**
### What this PR does (required):
- Do an emergency fix to the default user profile fetch.
With that the user auth function will be triggered correctly and get correct current user profile when log in

### CODE REVIEW

**Comment by JAFAJ0** [comment]
@simalicrum Just check here iand you can make full of your usage of getprofile getprofiles .etc, remove my parts at getprofile function, its yours now

**Comment by simalicrum** [comment]
At this point I think creating new functions is unnecessary. the /profile route on back end, getProfile function on the back end and getProfile API function on the front end are all yours. I've separated out my routes and frontend/backend functions completely to prevent any confusion with this route going forward. If you want to want to rename the functions or change them it won't impact me at all.

**Review by simalicrum — APPROVED** [review]
I think replicating the functions is redundant but please use the /profile route and original getProfile functions to meet your needs.

**Comment by JAFAJ0** [comment]
> I think replicating the functions is redundant but please use the /profile route and original getProfile functions to meet your needs.

My parts work now, if your parts do not work, revert it to your work function and reuse get profile.

**Pull request merged**
